version: 2.0

jobs:
            
  build:
    parallelism: 2
    docker: 
      - image: docker:17.06
      - image: docker:17.06
    steps:
      - run: apk add --no-cache git openssh curl
      #- run: curl https://raw.githubusercontent.com/michaelcontento/circleci-matrix/master/src/circleci-matrix.sh -o /usr/local/bin/circleci-matrix \
       #     && chmod +x /usr/local/bin/circleci-matrix
      - run: curl -fsSL http://git.io/v2Ifn | sh
      - checkout
      - run: echo hi
      - run: ~/.local/bin/circleci-matrix
